<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Laporan Penilaian Kinerja</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            font-size: 12px;
            padding: 20px;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }
        .header h1 {
            font-size: 18px;
            margin: 0;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f5f5f5;
            font-weight: bold;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
        .predikat-badge {
            padding: 3px 8px;
            border-radius: 12px;
            font-size: 10px;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>LAPORAN PENILAIAN KINERJA PEGAWAI</h1>
        <p>BPRS Amanah Bangsa</p>
        <p>Periode: {{ $periode->nama }}</p>
        <p>Tanggal Cetak: {{ date('d/m/Y H:i') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th width="5%">No</th>
                <th width="20%">Nama Pegawai</th>
                <th width="15%">NIP</th>
                <th width="10%">Self</th>
                <th width="10%">Atasan</th>
                <th width="10%">Penilai</th>
                <th width="10%">Nilai Akhir</th>
                <th width="15%">Predikat</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data as $index => $d)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $d->pegawai->nama }}</td>
                <td>{{ $d->pegawai->nip }}</td>
                <td>{{ $d->nilai_self ?? '-' }}</td>
                <td>{{ $d->nilai_atasan_langsung ?? '-' }}</td>
                <td>{{ $d->nilai_atasan_penilai ?? '-' }}</td>
                <td><strong>{{ $d->nilai_akhir }}</strong></td>
                <td>
                    <span class="predikat-badge" 
                          style="color: {{ $d->predikat->warna_text ?? '#000' }}; 
                                 background-color: {{ $d->predikat->warna_latar ?? '#ccc' }}">
                        {{ $d->predikat->nama ?? '-' }}
                    </span>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div style="margin-top: 20px;">
        <p><strong>Ringkasan:</strong></p>
        <ul>
            <li>Total Pegawai: {{ $data->count() }}</li>
            <li>Rata-rata Nilai: {{ number_format($data->avg('nilai_akhir'), 2) }}</li>
        </ul>
    </div>

    <div class="footer">
        <p>&copy; {{ date('Y') }} BPRS Amanah Bangsa - Laporan generated by sistem</p>
    </div>
</body>
</html>